language: go
env:
  global:
    secure: VODLlKrwGXdHDhd1SganzfXp4Fb0bYxBvRypwsEa7Tu2eNvK3H1E9VgR3xNgpJIX2v+3UvlUNV3pSYj+c5Gi33qFc1I3jBEsk3umK4Ajkmf749eWS1axMl0Y2NNi8Oha/1fVG31O5NavPeafQhCoH6XXWSqQwQiGRrshY5rMeBg=
go:
- 1.4
install:
- go get ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN